name: Create Email.Contracts NuGet package

on:
  workflow_dispatch:

jobs:
  publish_nuget_package:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          dotnet tool restore
          dotnet restore Amatsucozy.PMS.Email.Contracts/Amatsucozy.PMS.Email.Contracts.csproj

      - name: Pack
        run: dotnet pack Amatsucozy.PMS.Email.Contracts/Amatsucozy.PMS.Email.Contracts.csproj --no-restore -c Release

      - name: Push
        run: dotnet nuget push Amatsucozy.PMS.Email.Contracts/bin/Release/Amatsucozy.PMS.Email.Contracts.${env:NBGV_NuGetPackageVersion}.nupkg -s "github" -k ${{ secrets.GITHUB_TOKEN }}
