name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup credentials
      run: dotnet nuget add source --username Amatsucozy --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github-workflow "https://nuget.pkg.github.com/Amatsucozy/index.json"

    - name: Install dependencies
      run: |
        dotnet tool restore
        dotnet restore Amatsucozy.PMS.Email.sln
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag amatsucozy/amatsucozy.pms.email:1.0 amatsucozy/amatsucozy.pms.email:latest
      
    - name: Push the Docker image
      run: docker push amatsucozy/amatsucozy.pms.email:latest
